name: Connect Button WebSocket Test

on:
  push:
    branches: [ main ]
    paths:
      - 'client/public/simple-student.html'
      - 'server/services/WebSocketServer.ts'
      - 'server/services/TranslationService.ts'
  pull_request:
    branches: [ main ]
    paths:
      - 'client/public/simple-student.html'
      - 'server/services/WebSocketServer.ts'
      - 'server/services/TranslationService.ts'
  workflow_dispatch:  # Allow manual triggering

jobs:
  connect-button-test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run Connect Button WebSocket Test
        run: |
          # Create test results directory
          mkdir -p test-results
          
          # Run the direct WebSocket test
          chmod +x run-connect-button-direct-test.sh
          ./run-connect-button-direct-test.sh
        
      - name: Upload test results
        if: always()  # Upload logs even on test failure
        uses: actions/upload-artifact@v3
        with:
          name: connect-button-test-results
          path: |
            test-results/
            server-output.log