name: Teacher TTS Service Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  tts-service-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
      
      - name: Start server in background
        run: |
          npm run dev &
          sleep 5
          
      - name: Install Chrome
        run: |
          wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google.list
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable
          
      - name: Install Selenium and WebDriver
        run: |
          npm install selenium-webdriver
          npm install chromedriver
          
      - name: Run TTS auto-play verification test
        run: |
          export TEST_URL=http://localhost:5000
          export OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}
          node tests/selenium/tts_autoplay_verification.js
        env:
          CI: true
          
      - name: Verify TTS service functionality
        run: |
          echo "TTS Service Auto-Play Test completed successfully"
          echo "✓ Verified that both OpenAI TTS and Browser TTS services auto-play correctly"
          echo "✓ Verified that TTS service selection is properly maintained"