name: TTS Service Selection Tests

on:
  push:
    branches: [ main ]
    paths:
      - 'client/public/simple-student.html'
      - 'server/services/TextToSpeechService.ts'
      - 'server/services/WebSocketServer.ts'
      - 'tests/e2e/tts-service-selection.test.js'
  pull_request:
    branches: [ main ]
    paths:
      - 'client/public/simple-student.html'
      - 'server/services/TextToSpeechService.ts'
      - 'server/services/WebSocketServer.ts'
      - 'tests/e2e/tts-service-selection.test.js'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Install Chrome
      run: |
        wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
        echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable
      
    - name: Start server
      run: |
        npm run dev &
        sleep 10
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        
    - name: Run TTS service selection tests
      run: |
        APP_URL=http://localhost:3000 npm test -- tests/e2e/tts-service-selection.test.js
        
    - name: Update test results metrics
      if: always()
      run: |
        echo "Updating test metrics dashboard with TTS service selection test results"
        # This would update the metrics database with test results
        node test-metrics-api.js --test-type=e2e --test-name=tts-service-selection --update-results