name: TTS Service Selection Tests

on:
  push:
    branches: [ main ]
    paths:
      - 'client/public/simple-student.html'
      - 'server/services/TextToSpeechService.ts'
      - 'server/services/WebSocketServer.ts'
      - 'tests/e2e/**/*.ts'
  pull_request:
    branches: [ main ]
    paths:
      - 'client/public/simple-student.html'
      - 'server/services/TextToSpeechService.ts'
      - 'server/services/WebSocketServer.ts'
      - 'tests/e2e/**/*.ts'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Install Chrome
      run: |
        wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
        echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable
      
    - name: Start server
      run: |
        npm run dev &
        sleep 10
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        
    - name: Run TTS service selection tests
      run: |
        # Run E2E tests using Vitest
        npx vitest run --config test-config/vitest/vitest.e2e.config.mjs
      env:
        APP_URL: http://localhost:5000
        
    - name: Update test results metrics
      if: always()
      run: |
        echo "TTS service selection test results completed"
        echo "Test metrics would be updated here in a real implementation"